config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :contents
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :user

  validates :title,  presence: true
  has_many :tag_contents, dependent: :destroy
  has_many :tags, through: :tag_contents
  has_rich_text :description
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, uniqueness: {scope: :user}

  has_many :tag_contents, dependent: :destroy
  has_many :contents, through: :tag_contents
end

app/models/tag_content.rb
class TagContent < ApplicationRecord
  belongs_to :tag
  belongs_to :content
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contents 
  has_many :tags 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_content, only: [:show , :update, :edit, :destroy]
  
  def index 
    
    @contents = current_user.contents.with_rich_text_description_and_embeds
    tag_titles = params[:tags]
    
    if tag_titles.present?
      @contents = @contents.joins(:tags).where(tags: { title: tag_titles }).distinct 
    end

  end

  def new  
    @content = Content.new
  end

  def create
    @content = Content.create(content_params)
    @content.user = current_user
    if @content.save 
      associated_tags!
      redirect_to contents_path, notice: 'Content was successfully created!'
    else
      render :new
    end
  end

  def edit; end

  def update 
    if @content.update(content_params)
      associated_tags!
      redirect_to contents_path, notice: 'Content was successfully updated!'
    else
      render :edit 
    end
  end

  def show;  end

  def destroy 
    @content.destroy
    redirect_to contents_path, notice: 'Content was successfully detroyed!'
  end
  private 

  def content_params 
    params.require(:content).permit(:title, :description, :tags)
  end

  def tags_params 
    params.require(:content).permit(tags: [])[:tags].reject(&:blank?)
  end

  def associated_tags!
    tags = tags_params.map do |tag_title| 
      current_user.tags.where(title: tag_title).first_or_initialize
    end
    @content.tags = tags
  end
  def set_content 
    @content = Content.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @tags_data = current_user.contents.joins(:tags).group('tags.title').count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
       
    if level == "alert"
         "alert alert-warning alert-dismissible fade show"
    elsif level == "notice"     
         "alert alert-success alert-dismissible fade show"
    elsif level == "error" 
         "alert alert-danger alert-dismissible fade show"
    else
         "alert alert-primary alert-dismissible fade show"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/contents/_form.html.erb
<% if content.errors.any? %>
  <%= content.errors.full_messages.join(', ')%>
<% end %>

<%= form_with(model: content, local: true)  do |form| %>
<div class="form-group">
  <%= form.label :title %>
  <%= form.text_field :title , class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :description %>
  <%= form.rich_text_area :description  %>
</div>
<div class="form-group">
  <%= form.label :tags %>
  <%= form.select :tags, options_for_select(current_user.tags.pluck(:title) , content.tags.pluck(:title)), {}, { class: 'select2 form-control', multiple: 'multiple' } %>
</div>
<br/>

<div class="mt-2">
  <%= form.submit 'Enviar', class: 'btn btn-primary' %>
</div>

<% end %>

<div class="pt-3">
  <%= link_to 'Voltar', contents_path %>
</div>

app/views/contents/edit.html.erb
<h1>Editando Conteúdo</h1>
<div class="pt-3">
  <%= render 'form', content: @content %>
</div>

app/views/contents/index.html.erb
<section class="py-1">
  <%= form_tag(contents_path, method: :get) do %>
  <div class="form-group mt-3 col-sm-10">
    Filtar por Tags: 
    <%= select_tag "tags[]", options_for_select(current_user.tags.pluck(:title), params[:tags]),  class: 'select2 form-control ', multiple: 'multiple'%>
  </div>
  
  
  <div class="mb-1 mt-1">
    <%= submit_tag('Pesquisar', class: 'btn btn-danger') %>
  </div>
  <% end %>
  
  <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Title</th>
        <th>Tags </th>
        <th colspan="3"> <%= link_to 'Novo Conteúdo', new_content_path %> </th>
      </tr>
    </thead>
    <tbody>
      <% @contents.each do |content| %>
      <tr>
        <td><%= content.id %></td>
        <td> <%= content.title %> </td>
        <td> <%= content.tags.pluck(:title).join(', ') %> </td>
        <td> <%= link_to 'Editar', edit_content_path(content) %> </td>
        <td>
          <%= link_to 'Exibir', content_path(content) %>
        </td>
        <td>
          <%= link_to 'Excluir', content_path(content), method: :delete, data: { confirm: 'Você está certo disso ?' } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  
  
</section>

app/views/contents/new.html.erb
<h1>Novo Conteudo</h1>

<%= render 'form', content: @content %>

app/views/contents/show.html.erb
<p>
  <strong>Título</strong>: <%= @content.title %>
</p>

<p>
  <strong>Descrição</strong>: 
  <%= @content.description %>
</p>

<p>
  <strong>Dono</strong> : <%= @content.user.email %>
</p>

app/views/home/index.html.erb
<section class="py-5">
  <div id="box-mais-buscadas">
    <h2> Nuvem de Tags</h2>
  
    <% @tags_data.each do |tag_title, count| %>
    <p class="tags">
      <%= link_to tag_title, contents_path(tags: [tag_title]), class: (count > 9 ? "t9" : "t#{count}")  %>  
    </p>
    <% end %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mindapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %> <%= csp_meta_tag %> 
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= render "shared/navigation" %>
      
      <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>" role="alert">
              <%= value %>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>

      <%= yield %>

      
      <%= render "shared/footer" %>
      
    </div>   
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
      © 2021 Copyright: 
      
    </div>
    
  </div>
</footer>

app/views/shared/_navigation.html.erb
<% if current_user %>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                        <%= link_to 'Conteúdos',  contents_path, class: "nav-link active" %>
                    </li>
                    
                </ul>
<% end %>
            <% if current_user %> 
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false"> 
                            
                            <%= current_user.email %> 
                        
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                            
                            <li>
                                <%= link_to 'Logout', destroy_user_session_path, method: :delete,class: "dropdown-item" %>
                            </li>
                    </li>
                </ul>
            
            
            <% end %>
        </div>
    </div>
</nav>